
#OPERADOR DE IDENTIDADE IS (PARA SABER SE OCUPA A MESMO ESPAÇO DE MEMORIA DAS VARIAVEIS)
saldo = 1000
limite = 500

print(saldo is limite)

#OPERADOR DE IDENTIDADE IS NOT (PARA SABER SE REALMENTE NAO OCUPAM A MESMA REGIÃO DE MEMORIA )

print(saldo is not limite)