nome = "Rafael Filipe Avelar Da Silva"

#VAI APARECER A PRIMEIRA CARACTERE DO VALOR DA VARIAVEL
print(nome[0])
#VAI IR ATE O INDICE 9 DO CARACTERE
print(nome[:9])
#VAI COMEÇAR DO INDICE 10 E IR ATE O FINAL DA CADEIA DE CARACTERE
print(nome[10:])
#COMEÇA DO INDICE 10 E VAI ATE O 16 / 16 E ESPAÇO VAZIO VOLTA 1 CASA E VAI ATE O 15
print(nome[10:16])
#COMEÇA NO INDICE 10 VAI ATE O 16 PULANDO DE 2 EM 2
print(nome[10:16:2])
#RETORNA O VALOR COMPLETO 
print(nome[:])
#CRIA UMA COPIA DE STRING INVERTIDA
print(nome[::-1])
#PARA PEGAR A ULTIMA LETRA CARACTERE DA VARIAVEL POSSO COLOCAR -1 E ASSIM POR DIANTE
print(nome[-1])
